/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Quest model module.
 * @module model/Quest
 * @version 1.0.0
 */
class Quest {
    /**
     * Constructs a new <code>Quest</code>.
     * @alias module:model/Quest
     * @param paperD {String} 
     * @param lcodetools {String} 
     */
    constructor(paperD, lcodetools) { 
        
        Quest.initialize(this, paperD, lcodetools);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paperD, lcodetools) { 
        obj['paperD'] = paperD;
        obj['lcodetools'] = lcodetools;
    }

    /**
     * Constructs a <code>Quest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Quest} obj Optional instance to populate.
     * @return {module:model/Quest} The populated <code>Quest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Quest();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('paperD')) {
                obj['paperD'] = ApiClient.convertToType(data['paperD'], 'String');
            }
            if (data.hasOwnProperty('lcodetools')) {
                obj['lcodetools'] = ApiClient.convertToType(data['lcodetools'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Quest.prototype['_id'] = undefined;

/**
 * @member {String} paperD
 */
Quest.prototype['paperD'] = undefined;

/**
 * @member {String} lcodetools
 */
Quest.prototype['lcodetools'] = undefined;






export default Quest;

